### PR TITLE
Multiple printers using USB adapter

### PR DESCRIPTION
**Pull request by jor3l**
Sup song,

I needed support for multiple printers using USB and implemented this, it should work as is for people using only one printer but if you need more you can switch them easy.

Docs are also updated to explain how to use it.

### CODE REVIEW

**Comment by jor3l** [comment]
Seems like travis failed to install the USB module... 🤔

**Comment by song940** [comment]
@jor3l ehh... yeah. so, i plan move out adapters from escpos package.

**Comment by song940** [comment]
and, for mutiple adapters support, i want to like this ...

```js
'use strict';
const escpos = require('escpos');

const devices = escpos.USB.findPrinter();
const network = new escpos.Network('localhost');
const lp0     = new escpos.Serial('/dev/usb/lp0');
const usb     = escpos.USB(0x01, 0xff);

const printer = new escpos.Printer([
  devices[1],
  devices[3],
  network,
  lp0,
  usb
]);

device.open(function(){

  printer
  .font('a')
  .align('ct')
  .style('bu')
  .size(1, 1)
  .text('The quick brown fox jumps over the lazy dog')
  .text('敏捷的棕色狐狸跳过懒狗')
  .barcode('12345678', 'EAN8')
  .qrimage('https://github.com/song940/node-escpos', function(err){
    this.cut();
    this.close();
  });

});
```

**Comment by jor3l** [comment]
What if the Printer does it all? Something like:
`const printer = new escpos.Printer([{type: "usb", name: "kitchen"}, {type: "usb", name: "bar"}, {type: "network", name:"lobby"]);`

Each usb will be assigned based on the index they appear, if the bar is not connected will be undefined.

And later we can use: 

`printer
  .to('kitchen')
  .font('a')
  .align('ct')
  .style('bu')
  .size(1, 1)
  .text('The quick brown fox jumps over the lazy dog')
  .text('敏捷的棕色狐狸跳过懒狗')
  .barcode('12345678', 'EAN8')
  .qrimage('https://github.com/song940/node-escpos', function(err){
    this.cut();
    this.close();
  });`

Also, Printer should be able to tell if the device is open/claimed and so on.

**Pull request merged**
