### PR TITLE
Added method to reverse colors

### PR DESCRIPTION
**Pull request by lbarthon**
Hey,

I needed a method to reverse the colors, I used termcaps from escpos-php (see this https://github.com/mike42/escpos-php/blob/development/src/Mike42/Escpos/Printer.php at line 935, method setReverseColors), and added them in the library so everyone can use it.
It basically change black text on white background to white text on black background.

Thanks,
lbarthon

### CODE REVIEW

**Comment by lbarthon** [comment]
It looks like this: https://i.barthonet.ovh/TRMFGd6S

**Comment by lbarthon** [comment]
Sorry to bump @song940, will you upgrade the current version to add it, or should I have done it in the PR ?

**Comment by song940** [comment]
+ escpos@2.5.2

**Comment by lbarthon** [comment]
Thanks !

**Pull request merged**
